### ISSUE TITLE
PV RCNN++ pretained model

### ISSUE THREAD

**Issue by JunLFang** [open-mmlab/OpenLidarPerceptron#1636]
Dear developer, if possible ,  could you please provide the PV RCNN++ pretrained model?
Thank you very much

**Comment by kmodexc** [comment]
In the readme it says: "We could not provide the above pretrained models due to [Waymo Dataset License Agreement](https://waymo.com/open/terms/), but you could easily achieve similar performance by training with the default configs."

If they have it i would love to have it too but looks like we have to train by ourselves.
