### ISSUE TITLE
How to choose anchor_range?

### ISSUE THREAD

**Issue by monghimng** [open-mmlab/OpenLidarPerceptron#94]
Hi, I am wondering how did the author choose anchor_range in the yaml files. For example, anchors for cars are set up as:

```
{'anchor_range': [0, -40.0, -1.78, 70.4, 40.0, -1.78],
                     'sizes': [[1.6, 3.9, 1.56]],
                     'rotations': [0, 1.57],
                     'matched_threshold': 0.6,
                     'unmatched_threshold': 0.45,
                     'class_name': 'Car'},
```

I understand the choice of [0, 70.4] in the dimension of x and [-40, 40] in the dimension of y because that's the range that corresponds to the FOV of the image_2 in KITTI. However, I don't understand the choice of `-1.78`, since the ground is at -3 (judging from the point range in the voxel generator) and car anchor height is 1.56meter. Is this number calculated in some way?

In addition, how did the author choose -3 as the ground? Is this calculated somehow empirically or hand picked?

Thanks.

**Comment by Divadi** [comment]
On the KITTI dataset, papers use an a car anchor centered along the z-axis at -1.
In this config, it's not the center of the z-axis but rather the bottom of the car in the z-axis. Since the car anchor is height 1.56, half is 0.78, so the center - half the height becomes -1.78.
As for -3, all the papers use it, and I don't think there are very many points below -3 in velodyne coords
